#!/usr/bin/env bash
# SessionStart hook - injects the Python service invariants as always-on context.
# These under-trigger as auto-load skills because they fire on implicit mid-turn decisions
# with no signal in the user's prompt. The detailed patterns and code stay in the skills
# (load on demand for depth); this block is the compact enforcement layer. Self-sufficient:
# works when this plugin is enabled alone. Pure-shell (bash), no Node required; wired via
# hooks/hooks.json. The payload below is static JSON.
cat <<'JSON_EOF'
{"systemMessage":"ceh-python-service: loading Python service invariants for this session.","hookSpecificOutput":{"hookEventName":"SessionStart","additionalContext":"PYTHON SERVICE INVARIANTS (ceh-python-service) — apply to all Python work in this project.\nThese are non-negotiable defaults. For full patterns and code behind any rule, load the matching\nskill via the Skill tool as `ceh-python-service:<name>`, where `<name>` is the tag shown in\nbrackets below (e.g. `ceh-python-service:python-security`).\n\nStyle & types [python-service-environment]:\n- Type hints on every function signature and class attribute. Use 3.12 built-in generics (`list[str]`, not `List[str]`).\n- No `Any` without a comment explaining why. No `# type: ignore` without a comment. Never downgrade mypy `strict = true` to silence errors.\n- ruff only for lint/format — not flake8, pylint, isort, or Black. `snake_case` functions/vars, `PascalCase` classes, `UPPER_SNAKE_CASE` constants.\n- Pydantic v2 `BaseModel` for all request/response types and domain entities. Use `await asyncio.sleep()`, never `time.sleep()`. All I/O is awaited.\n\nSecurity [python-security]:\n- Secrets via `pydantic-settings` (`BaseSettings`) from `.env` — never hard-coded; `.env` is never committed.\n- Validate all input at the API boundary with Pydantic. Parameterized SQL always — never interpolate user input into queries.\n- `ConfigDict(extra='forbid')` on all external-input / LLM output models; validate LLM output before any state mutation.\n- CORS explicit — no wildcard origins in production. Rate-limit mutation endpoints. Session tokens: `secrets.token_urlsafe(32)`, never logged, never in URLs.\n- Run pip-audit before every release.\n\nLogging [python-observability]:\n- structlog with an event name + key=value pairs. Never log secrets, tokens, credentials, full session/LLM content, query params containing user data, or PII.\n- Every request carries a `correlation_id`: generated at the boundary if absent, propagated through service calls, included in every log entry, returned as `X-Correlation-ID`.\n- Do not log at INFO on every request — use DEBUG for high-frequency events."}}
JSON_EOF
