#!/usr/bin/env bash
# SessionStart hook - injects the frontend invariants as always-on context.
# These under-trigger as auto-load skills because they fire on implicit mid-turn decisions
# with no signal in the user's prompt. The detailed patterns and code stay in the skills
# (load on demand for depth); this block is the compact enforcement layer. Self-sufficient:
# works when this plugin is enabled alone. Pure-shell (bash), no Node required; wired via
# hooks/hooks.json. The payload below is static JSON.
cat <<'JSON_EOF'
{"systemMessage":"ceh-web-frontend: loading frontend invariants for this session.","hookSpecificOutput":{"hookEventName":"SessionStart","additionalContext":"FRONTEND INVARIANTS (ceh-web-frontend) — apply to all frontend work in this project.\nStack: Bun + Vite, SvelteKit or React. These are non-negotiable defaults. For full patterns and\ncode behind any rule, load the matching skill via the Skill tool as `ceh-web-frontend:<name>`,\nwhere `<name>` is the tag shown in brackets below (e.g. `ceh-web-frontend:accessibility`).\n\nTypes & style [environment]:\n- Never use `any` — use `unknown` with narrowing. Prefer `undefined` over `null`. Use `?.`/`??`, not `||` for defaults (it collapses `0`, `''`, `false`).\n- `type` is the default; `interface` only when you need declaration merging. No TS `enum` — use `as const` objects. tsconfig `strict: true`; never `// @ts-ignore`.\n- Naming: `camelCase` vars/functions, `PascalCase` types and component files, `UPPER_SNAKE_CASE` constants. Import local code via the path alias, never deep relative paths.\n\nComponents & data flow [sveltekit / react-vite]:\n- Components are presentational — they render props and call callbacks; business logic lives in services/hooks/stores, not in render.\n- Shared state is updated only from API responses — components never mutate shared state directly; pass callbacks/props instead.\n- All `fetch` goes through the centralized API client (`$lib/api`) — components never call `fetch` directly.\n- SvelteKit: Svelte 5 runes (`$props`/`$state`/`$derived`), `onclick` not `on:click`, `error()`/`redirect()` from `@sveltejs/kit`. React: Rules of Hooks, exhaustive effect deps, error boundaries.\n\nAccessibility [accessibility]:\n- Native semantic HTML first (`<button>`, `<nav>`, `<main>`) — never a `<div>` with `role=\"button\"`. Add ARIA only when no native element fits.\n- Every mouse action must be keyboard-reachable. Never remove the focus indicator. Images need `alt` (empty `alt=\"\"` for decorative).\n- Text contrast >= 4.5:1 (3:1 for large text). Never convey meaning by color alone. Fix all a11y warnings before opening a PR.\n\nEnvironment [environment]:\n- Bun is the runtime and package manager; never edit the lockfile manually. Never commit `.env`."}}
JSON_EOF
